name: Master
on:
  push:
    branches:
      - master

jobs:
  # publish to gh-pages (& IPFS when a release is detected)
  www:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    strategy:
      matrix:
        step: ['build:release:www']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT_BOT }}
    - uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
    - name: ${{ matrix.step }}
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CRUST_SEEDS: ${{ secrets.CRUST_SEEDS }}
        GH_PAGES_SRC: packages/apps/build
        GH_PAT: ${{ secrets.GH_PAT_BOT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT_BOT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_SECRET_KEY: ${{ secrets.PINATA_SECRET_KEY }}
      run: |
        yarn install --immutable
        yarn ${{ matrix.step }}